# Auto-labeler configuration for PRs
# Label PRs based on changed files

backend:
  - changed-files:
    - any-glob-to-any-file: 'app/api/**/*'
    - any-glob-to-any-file: 'app/services/**/*'
    - any-glob-to-any-file: 'app/models/**/*'

frontend:
  - changed-files:
    - any-glob-to-any-file: 'app/frontend/**/*'

database:
  - changed-files:
    - any-glob-to-any-file: 'alembic/**/*'
    - any-glob-to-any-file: 'app/models/**/*'

docker:
  - changed-files:
    - any-glob-to-any-file: 'Dockerfile*'
    - any-glob-to-any-file: 'docker-compose*.yml'
    - any-glob-to-any-file: '.dockerignore'

ci-cd:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**/*'
    - any-glob-to-any-file: '.github/dependabot.yml'

documentation:
  - changed-files:
    - any-glob-to-any-file: '*.md'
    - any-glob-to-any-file: 'docs/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file: 'pyproject.toml'
    - any-glob-to-any-file: 'poetry.lock'

tests:
  - changed-files:
    - any-glob-to-any-file: 'tests/**/*'
    - any-glob-to-any-file: 'test_*.py'

configuration:
  - changed-files:
    - any-glob-to-any-file: 'app/config/**/*'
    - any-glob-to-any-file: '.env.example'
    - any-glob-to-any-file: 'alembic.ini'
