version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: musicmood-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: musicmood_user
      POSTGRES_PASSWORD: musicmood_pass
      POSTGRES_DB: musicmood
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U musicmood_user -d musicmood"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - musicmood-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: musicmood-redis
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - musicmood-network

  # pgAdmin (Optional - Web UI for PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: musicmood-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@musicmood.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - musicmood-network
    profiles:
      - tools  # Only start with: docker-compose --profile tools up

  # Redis Commander (Optional - Web UI for Redis)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: musicmood-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - musicmood-network
    profiles:
      - tools  # Only start with: docker-compose --profile tools up

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  musicmood-network:
    driver: bridge
