blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/yourusername/musicmood/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Vulnerability
    url: https://github.com/yourusername/musicmood/security/advisories/new
    about: Report security vulnerabilities privately
