# CI/CD Pipeline - Docker Build and Push
# DISABLED: GitHub free runners don't have sufficient disk space for Docker builds
# Docker images must be built and pushed locally using the provided script
# See: scripts/docker-push.ps1
name: CD - Docker Build & Push (DISABLED)

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'This workflow is disabled. Use scripts/docker-push.ps1 instead.'
        required: false

# Entire workflow disabled due to GitHub runner disk space limitations
# To build and push Docker images:
# 1. Run: .\scripts\docker-push.ps1 -Version "v1.0.0"
# 2. Or manually:
#    docker build -t ghcr.io/vaibhavkarsh/musicmood-backend:latest -f Dockerfile.backend .
#    docker build -t ghcr.io/vaibhavkarsh/musicmood-frontend:latest -f Dockerfile.frontend .
#    docker push ghcr.io/vaibhavkarsh/musicmood-backend:latest
#    docker push ghcr.io/vaibhavkarsh/musicmood-frontend:latest

jobs:
  disabled-notice:
    name: Workflow Disabled - Use Local Script
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        run: |
          echo "================================================"
          echo "This workflow is disabled due to disk space limitations"
          echo "Build and push Docker images locally instead:"
          echo "  .\scripts\docker-push.ps1 -Version 'v1.0.0'"
          echo "================================================"
          exit 1
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
